-- Créer la table job_categories si elle n'existe pas
CREATE TABLE IF NOT EXISTS public.job_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    description text,
    created_at timestamptz DEFAULT now() NOT NULL
);

-- Activer RLS sur la table job_categories
ALTER TABLE public.job_categories ENABLE ROW LEVEL SECURITY;

-- Politique pour permettre la lecture à tous les utilisateurs authentifiés
CREATE POLICY "Enable read access for all authenticated users"
ON public.job_categories FOR SELECT
USING (auth.role() = 'authenticated');

-- Politique pour permettre la gestion par les recruteurs et admins
CREATE POLICY "Enable all access for recruiters and admins"
ON public.job_categories FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.users 
    WHERE id = auth.uid() AND role IN ('recruteur', 'admin')
  )
);

-- Insérer les catégories métier par défaut
INSERT INTO public.job_categories (name, description) VALUES 
('metier_eau', 'Métiers de l''eau et assainissement'),
('metier_electricite', 'Métiers de l''électricité et énergie'),
('metier_clientele', 'Métiers de la relation clientèle'),
('metier_support', 'Métiers du support et maintenance')
ON CONFLICT (name) DO NOTHING;
